model_selection:
    model:
      XGBClassifier:
        search_param_grid:
          max_dept:
           - 3          
           - 5
           - 7
           - 9
           - 11
          n_estimator:
           - 50
           - 100
           - 130
          random_state:
           - 0
           - 50
           - 100

      GaussainNB:
        search_param_grid:
          var_smoothing:
           - 0.5
           - 0.05
           - 0.01  


      Logistic_Regression:
        search_param_grid:
          C:
           - 500
           - 100
          max_iter:       
           - 100
           - 113

          multi_class:
           - 'auto'

          penalty:
           - 'l2'

          solver:
           - 'lbfgs'
           - 'liblinear'
           - 'sag'
           - 'saga'   
